# Generated by Django 4.0.4 on 2022-05-14 16:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facesets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faceset_token', models.CharField(max_length=50)),
                ('outer_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RollNumberToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_token', models.CharField(max_length=50)),
                ('roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_stud', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('query', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('0', 'IN PROGRESS'), ('1', 'ACCEPTED'), ('2', 'DECLINED')], default='0', max_length=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_stud', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('taken_by', models.ManyToManyField(related_name='%(app_label)s_%(class)s_stud', to=settings.AUTH_USER_MODEL)),
                ('taught_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_prof', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('is_present', models.CharField(choices=[('0', 'ABSENT'), ('1', 'PRESENT')], default='0', max_length=1)),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_prof', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_stud', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('course_id', 'student', 'date')},
            },
        ),
    ]
